server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/teachmeskills
    username: postgres
    password: postgres